export const Data = [
  { promtWord: "Country", word: "ARMENIA", id: 1 },
  { promtWord: "Mount", word: "ARARAT", id: 2 },
  { promtWord: "Sport", word: "BIATHLON", id: 3 },
  { promtWord: "Football Player", word: "MESSI", id: 4 },
  { promtWord: "FOOD", word: "CHEESE", id: 5 },
].sort(() => Math.random() - 0.5);

export const Letter = [
  { letter: "A", check: true },
  { letter: "B", check: true },
  { letter: "C", check: true },
  { letter: "D", check: true },
  { letter: "E", check: true },
  { letter: "F", check: true },
  { letter: "G", check: true },
  { letter: "H", check: true },
  { letter: "I", check: true },
  { letter: "J", check: true },
  { letter: "K", check: true },
  { letter: "L", check: true },
  { letter: "M", check: true },
  { letter: "N", check: true },
  { letter: "O", check: true },
  { letter: "P", check: true },
  { letter: "Q", check: true },
  { letter: "R", check: true },
  { letter: "S", check: true },
  { letter: "T", check: true },
  { letter: "U", check: true },
  { letter: "V", check: true },
  { letter: "W", check: true },
  { letter: "X", check: true },
  { letter: "Y", check: true },
  { letter: "Z", check: true },
];
